/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;


import DB.Dbconn;
import UserManagement.*;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import master.*;
import medicalstoremanagement.*;

/**
 *
 * @author user
 */


public class Damagestock extends javax.swing.JInternalFrame {

    /**
     * Creates new form attendance
     */
    
    String grno,dist_name,dist_addr,dist_cont,gr_date,prod_name,total_stock,brand;
    String error,prod_total_Stock;
    int Valid,grn;
    ResultSet rs_damage;
    Dbconn conn;
    DefaultTableModel modelItem;
    boolean no;
    int totalstock,damagedstock;
    int remainingstock;
    int selectedrow;
     public Connection con;

    
    JFrame frame = new JFrame();
    public Damagestock(JFrame parent, boolean modal) {
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        //System.out.println(dateFormat.format(date));
        jdamage_sysDatetxt.setText(dateFormat.format(date));
        
        //*********************** initialise D. Stock Number ***************
        
       increament();
        
        //********************* End of Initialisation***********************
       
       
       
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdamage_GRnumbertxt = new javax.swing.JTextField();
        jdamage_productnametxt = new javax.swing.JTextField();
        jdamage_GRdatetxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jdamage_sysDatetxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jdamage_Numbertxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jdamage_totalstocktxt = new javax.swing.JTextField();
        jdamage_damagedstocktxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jdamage_raminingstocktxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jdamage_Reason_combo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdamage_distributornametxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jdamage_addresstxt = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jdamage_contacttxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jdamage_desciptiontxt = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jdamage_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jdamage_updatebtn = new javax.swing.JButton();
        jdamage_clearbtn = new javax.swing.JButton();
        jdamage_backbtn = new javax.swing.JButton();

        setClosable(true);
        setTitle("Damge Stock");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1350, 550));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Product Details"));

        jLabel2.setText("G. R. No :");

        jLabel3.setText("Product Name");

        jLabel4.setText("G. R.. Date :");

        jdamage_GRnumbertxt.setToolTipText("Enter G. R. Number");
        jdamage_GRnumbertxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdamage_GRnumbertxtFocusLost(evt);
            }
        });

        jdamage_productnametxt.setToolTipText("");

        jdamage_GRdatetxt.setEditable(false);

        jLabel5.setText("Date:");

        jdamage_sysDatetxt.setEditable(false);

        jLabel10.setText("D.Stock No.");

        jdamage_Numbertxt.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jdamage_Numbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jdamage_GRnumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdamage_productnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdamage_GRdatetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jdamage_sysDatetxt))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jdamage_GRnumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jdamage_sysDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jdamage_Numbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jdamage_productnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdamage_GRdatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Damage Stock");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Damage Details"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Total"));

        jLabel6.setText("Total Stock :");

        jdamage_totalstocktxt.setEditable(false);

        jdamage_damagedstocktxt.setToolTipText("Enter Number of Damaged Stock");
        jdamage_damagedstocktxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdamage_damagedstocktxtFocusLost(evt);
            }
        });
        jdamage_damagedstocktxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdamage_damagedstocktxtKeyTyped(evt);
            }
        });

        jLabel7.setText("Damaged Stock :");

        jLabel8.setText("Remaining Stock :");

        jdamage_raminingstocktxt.setEditable(false);

        jdamage_Reason_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Breakage", "Write-Off", "Consumption of Own Stock", "Other" }));

        jLabel9.setText("Reason");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jdamage_raminingstocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdamage_totalstocktxt)
                            .addComponent(jdamage_damagedstocktxt)
                            .addComponent(jdamage_Reason_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdamage_Reason_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jdamage_totalstocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jdamage_damagedstocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdamage_raminingstocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(21, 21, 21))
        );

        jLabel11.setText("Distributor Name :");

        jdamage_distributornametxt.setEditable(false);

        jLabel12.setText("Address :");

        jdamage_addresstxt.setEditable(false);
        jdamage_addresstxt.setColumns(20);
        jdamage_addresstxt.setRows(5);
        jScrollPane2.setViewportView(jdamage_addresstxt);

        jLabel13.setText("Contact Number");

        jLabel14.setText("Description:");

        jdamage_desciptiontxt.setColumns(20);
        jdamage_desciptiontxt.setRows(5);
        jdamage_desciptiontxt.setToolTipText("Desciption If any");
        jScrollPane3.setViewportView(jdamage_desciptiontxt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdamage_distributornametxt)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jdamage_contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jdamage_distributornametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jdamage_contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Material Inward Table"));

        jdamage_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Brand", "Total Stock"
            }
        ));
        jdamage_table.setToolTipText("");
        jdamage_table.getTableHeader().setReorderingAllowed(false);
        jdamage_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdamage_tableMouseClicked(evt);
            }
        });
        jdamage_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdamage_tableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdamage_tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jdamage_table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jdamage_updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateicon.png"))); // NOI18N
        jdamage_updatebtn.setText("Save");
        jdamage_updatebtn.setEnabled(false);
        jdamage_updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdamage_updatebtnActionPerformed(evt);
            }
        });

        jdamage_clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clear-icon.png"))); // NOI18N
        jdamage_clearbtn.setText("Clear");
        jdamage_clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdamage_clearbtnActionPerformed(evt);
            }
        });

        jdamage_backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jdamage_backbtn.setText("Back");
        jdamage_backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdamage_backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jdamage_updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jdamage_clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdamage_backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jdamage_backbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdamage_clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdamage_updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void increament()
    {
         int x;
        String grx = null;
        ResultSet rs_grno;
        Dbconn conn = new Dbconn();
        rs_grno = conn.execute_query("Select MAX(Damage_Stock_No) from damage_stock where status=?", new String[]{"ACTIVE"});
        try {
            while(rs_grno.next())
            {
               //System.out.println(rs_grno.getString("MAX(GR_no)"));
                grx = rs_grno.getString("MAX(Damage_Stock_No)");
                if(grx==null)
                {
                    grx="0";
                }
             }
            x=Integer.parseInt(grx);
            x=x+1;
            grx=""+x;
            jdamage_Numbertxt.setText(grx);
        } catch (SQLException ex) {
            Logger.getLogger(Materialinward.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jdamage_clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdamage_clearbtnActionPerformed
jdamage_addresstxt.setText("");
        jdamage_contacttxt.setText("");
        jdamage_damagedstocktxt.setText("");
        jdamage_distributornametxt.setText("");
        jdamage_GRdatetxt.setText("");
        jdamage_GRnumbertxt.setText("");
        jdamage_productnametxt.setText("");
        jdamage_totalstocktxt.setText("");
        jdamage_raminingstocktxt.setText("");
        
        jdamage_desciptiontxt.setText("");
        jdamage_Reason_combo.setSelectedIndex(0);
        modelItem = (DefaultTableModel) jdamage_table.getModel();
        modelItem.setRowCount(0);
                
        


// TODO add your handling code here:
    }//GEN-LAST:event_jdamage_clearbtnActionPerformed

    private void jdamage_backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdamage_backbtnActionPerformed

        this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jdamage_backbtnActionPerformed

    
     public boolean Numbervalidate(String str)
            {  
                for (int i = 0; i < str.length(); i++) 
                {
                    if (!Character.isDigit(str.charAt(i)))          
                    return false;
                }
            return true; 
     
            } 
    
    private void jdamage_damagedstocktxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdamage_damagedstocktxtFocusLost

        try
        {
            jdamage_updatebtn.setEnabled(true);
            totalstock=Integer.parseInt(jdamage_totalstocktxt.getText());
            damagedstock = Integer.parseInt(jdamage_damagedstocktxt.getText());
            remainingstock=totalstock-damagedstock;       
            jdamage_raminingstocktxt.setText(Integer.toString(remainingstock));
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jdamage_damagedstocktxtFocusLost

    private void jdamage_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdamage_tableMouseClicked

     if(evt.getClickCount()==1)
        {
            JTable target = (JTable) evt.getSource();
            selectedrow = target.getSelectedRow();
            Object selectedcellvalue = target.getValueAt(selectedrow, 2);
            jdamage_totalstocktxt.setText((String) selectedcellvalue);
             selectedcellvalue = target.getValueAt(selectedrow, 0);
          jdamage_productnametxt.setText((String) selectedcellvalue);
           // refreshForm(selectedcellvalue);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jdamage_tableMouseClicked

    private void jdamage_updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdamage_updatebtnActionPerformed
    
        //******************* Validation OF the Form********************
        
        error="";
        Valid=0;
        if(jdamage_GRnumbertxt.getText().equals(""))
        {
            error+="\n"+"Please Enter The Goods Received Number.";
            Valid=1;
        }
        if(jdamage_productnametxt.getText().equals(""))
        {
            error+="\n"+"Please Enter The Product Name.";
            Valid=1;
        }
        if(jdamage_damagedstocktxt.getText().equals(""))
        {
            error+="\n"+"Please Enter the Damaged Stocks.";
            Valid=1;
        }
        
       
        
        
        int dmg,totl;
        dmg= Integer.parseInt(jdamage_damagedstocktxt.getText());
        totl =Integer.parseInt(jdamage_totalstocktxt.getText());
        
        if(dmg>totl)
        {
            error+="\n"+"Damaged Stock Can't be Greater than Total Stock.!";
            Valid=1;
        }

       
        if(Valid==1)
        {
            JOptionPane.showMessageDialog(rootPane, error, "Error", JOptionPane.ERROR_MESSAGE);
        } 
        else
        {
            int yesorNo;
            yesorNo =  JOptionPane.showConfirmDialog(rootPane, "Are you sure?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(yesorNo == 0)
            {
        //**************************************************************
        conn=new Dbconn();
//        String pno,pdate,did,dname,dadd,dofficeno,dmobno,demailid,dproductid,dproduproductname,dproductcategory,dproductorderqty,dproducttotalamount,postatus;
//        String vat_purchase,prcperunit,totalprice;.
        
        String dstock_no,Grno,grddate,damaeDate,prod_name,dist_name,dist_addr,dist_contact,reason,ttlstk,dmgstk,rmainingstk;
        String descrip,damage_status;
        int k=0;
        int r,c;
//            r=jmi_MaterialInwardTable.getRowCount();
//            c=jmi_MaterialInwardTable.getColumnCount();
//            JOptionPane.showMessageDialog(rootPane, r, "Rows",JOptionPane.ERROR_MESSAGE);
//            JOptionPane.showMessageDialog(rootPane, c, "Columns", JOptionPane.ERROR_MESSAGE);
       
//            for(int row=0; row<r;row++)
//           {
                dstock_no = jdamage_Numbertxt.getText();
                Grno=jdamage_GRnumbertxt.getText();            
                grddate=jdamage_GRdatetxt.getText();
                damaeDate = jdamage_sysDatetxt.getText();
                prod_name = jdamage_productnametxt.getText();
                dist_name = jdamage_distributornametxt.getText();
                dist_addr = jdamage_addresstxt.getText();
                dist_contact = jdamage_contacttxt.getText();
                reason = (String) jdamage_Reason_combo.getSelectedItem();
                ttlstk = jdamage_totalstocktxt.getText();
                dmgstk = jdamage_damagedstocktxt.getText();
                rmainingstk = jdamage_raminingstocktxt.getText();
                descrip = jdamage_desciptiontxt.getText();
                damage_status = "ACTIVE";
                  
            Dbconn co=new Dbconn();
            con=co.getConnection();
           
            String query = "INSERT INTO damage_stock(Damage_Stock_No,GR_number,  GRN_Date, dated, product_name,Distributor_Name,"
                    +"Distributor_Address, Distributor_Contact,Reason, total_stock ,damage_stock,remaining_stock,"
                    +"description,status)"
                    + " VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) " ;
            String status="ACTIVE";
            try
            {
                PreparedStatement pst=con.prepareStatement(query);
                pst.setString(1, dstock_no);
                pst.setString(2, Grno);
                pst.setString(3, grddate);
                pst.setString(4,  damaeDate);
                pst.setString(5, prod_name);
                pst.setString(6, dist_name);
                pst.setString(7, dist_addr);
                pst.setString(8, dist_contact);
                pst.setString(9, reason);
                pst.setString(10, ttlstk);
                pst.setString(11, dmgstk);
                pst.setString(12, rmainingstk);
                pst.setString(13, descrip);
                pst.setString(14, damage_status);
                k=pst.executeUpdate();
               
                
             //************ Remaining Stock Updation In mi table And Product table ********
                 try
            {
                Dbconn coon = new Dbconn();
                //con = coon.getConnection();

            String remain_stock,dmg_prod_name;
           remain_stock = jdamage_raminingstocktxt.getText();
           dmg_prod_name = jdamage_productnametxt.getText();

                int i = coon.update_data("update product_info SET totalstock =?"
                  +" where product_name=?" , new String[]{remain_stock,dmg_prod_name});
                if(i>0)
                {
                    //JOptionPane.showMessageDialog(rootPane, "Rows Updated", "Successful", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                   // JOptionPane.showMessageDialog(rootPane, "Not Saved", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
//                i = coon.update_data("update material_inward_info SET Total_Stock =?"
//                  +" where product_name=?" , new String[]{remain_stock,dmg_prod_name});
//                   if(i>0)
//                {
//                    //JOptionPane.showMessageDialog(rootPane, "Rows Updated", "Successful", JOptionPane.INFORMATION_MESSAGE);
//                }
//                else
//                {
//                   // JOptionPane.showMessageDialog(rootPane, "Not Saved", "Error", JOptionPane.ERROR_MESSAGE);
//                }     
               ///********************** Clear All the data After Update ********************
                   
                   jdamage_GRnumbertxt.setText("");
                   jdamage_GRdatetxt.setText("");
                   jdamage_productnametxt.setText("");
                   jdamage_distributornametxt.setText("");
                   jdamage_contacttxt.setText("");
                   jdamage_addresstxt.setText("");
                   jdamage_desciptiontxt.setText("");
                   jdamage_Reason_combo.setSelectedIndex(0);
                   jdamage_raminingstocktxt.setText("");
                   jdamage_totalstocktxt.setText("");
                   jdamage_damagedstocktxt.setText("");
                   
                   modelItem = (DefaultTableModel) jdamage_table.getModel();
                   modelItem.setRowCount(0);
                   increament();
                   
                 //***************************************************************************  
       
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
           
                
             //********************** End Of Updation *************************************
           }
         catch(Exception ex)
         {
             JOptionPane.showMessageDialog(rootPane, ex, "Error", JOptionPane.ERROR_MESSAGE);
         }
 
             if(k>0)
        {
        JOptionPane.showMessageDialog(rootPane, "Data Saved Sucessfully", "SAVE", JOptionPane.INFORMATION_MESSAGE);
    
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Data Not Saved", "Warning!", JOptionPane.YES_NO_OPTION);
    
        }
    
//        }    
        

            
    }
        
        
        
        
        
        
        
 
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jdamage_updatebtnActionPerformed

    private void jdamage_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdamage_tableKeyPressed

        JTable target = (JTable)evt.getSource();  
        if((evt.getKeyCode()==KeyEvent.VK_UP)|| evt.getKeyCode()==KeyEvent.VK_DOWN)
    {   
      selectedrow= target.getSelectedRow();  
      Object selectedCellValue=target.getValueAt(selectedrow, 2);  
      jdamage_totalstocktxt.setText(selectedCellValue.toString());
        selectedCellValue = target.getValueAt(selectedrow, 0);
          jdamage_productnametxt.setText((String) selectedCellValue);
    }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jdamage_tableKeyPressed

    private void jdamage_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdamage_tableKeyReleased


        JTable target = (JTable)evt.getSource();  
        if((evt.getKeyCode()==KeyEvent.VK_UP)|| evt.getKeyCode()==KeyEvent.VK_DOWN)
    {   
      selectedrow= target.getSelectedRow();  
      Object selectedCellValue=target.getValueAt(selectedrow, 2);  
          jdamage_totalstocktxt.setText((String) selectedCellValue);
          selectedCellValue = target.getValueAt(selectedrow, 0);
          jdamage_productnametxt.setText((String) selectedCellValue);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_jdamage_tableKeyReleased

    private void jdamage_damagedstocktxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdamage_damagedstocktxtKeyTyped

        char c = evt.getKeyChar();

        if (!((c >= '0') && (c <= '9') || (c == '.')  || (c == java.awt.event.KeyEvent.VK_BACK_SPACE) || (c == java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
           
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jdamage_damagedstocktxtKeyTyped

    private void jdamage_GRnumbertxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdamage_GRnumbertxtFocusLost

          grno = jdamage_GRnumbertxt.getText();
        error="";
        Valid=0;
        modelItem = (DefaultTableModel) jdamage_table.getModel();
        modelItem.setRowCount(0);
        
        conn= new Dbconn();
        if(grno.equals(""))
        {
            error+="\n"+"Please Ener the G.R. Number.!";
            Valid=1;            
        }
        
        if(Valid==1)
        {
            JOptionPane.showMessageDialog(rootPane, error, "Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
           // JOptionPane.showMessageDialog(rootPane, error, "Success", JOptionPane.ERROR_MESSAGE);
           try
           {
               modelItem=(DefaultTableModel)jdamage_table.getModel();
               modelItem.setRowCount(0);
               
               
               conn=new Dbconn();
               //********************* Fetching Material Inward_Info Details*****************
                rs_damage=conn.execute_query("Select * from material_inward_info where GR_no=?", new String[]{grno});
               //
               while(rs_damage.next())
               {             
                    jdamage_GRdatetxt.setText(rs_damage.getString("GR_date"));
                    dist_name=(rs_damage.getString("distributors_name"));  
                    jdamage_distributornametxt.setText(dist_name);
                    
                    //****table Contents*************
                    
                    prod_name=rs_damage.getString("product_name");
                    total_stock=rs_damage.getString("Total_Stock");
                    brand=rs_damage.getString("Brand");
                    
                    modelItem.addRow(new String[]{prod_name, brand,total_stock});
               }
               //************* Adjusting Total stock According to Product Table **********
               
               int r =jdamage_table.getRowCount();
               int c = jdamage_table.getColumnCount();
               for(int row=0;row<r;row++)
               {
                   prod_name = (String) jdamage_table.getValueAt(row, 0);
                   conn = new Dbconn();
                   rs_damage = conn.execute_query("Select * from product_info where product_name =?",new String[]{prod_name});
                   while(rs_damage.next())
                   {
                       prod_total_Stock=rs_damage.getString("totalstock");                       
                   }
                  // modelItem = (DefaultTableModel) jdamage_table.getModel();
                   jdamage_table.setValueAt(prod_total_Stock, row, 2);
                  
                   
               }
               
               
               //********************* End Of adjusting **************************
               //************* Fetching Distributor Details**********************
               rs_damage=conn.execute_query("Select * from distributors_details where distributors_name=?", new String[]{dist_name});
                while(rs_damage.next())
               {             
                    jdamage_addresstxt.setText(rs_damage.getString("distributors_address"));
                   jdamage_contacttxt.setText(rs_damage.getString("distributors_mobileno"));  
                    
               }
                //****************************************************************
                
                
               
                

           }
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(rootPane, e, "Error", JOptionPane.ERROR_MESSAGE);
           }
          
        }// TODO add your handling code here:
    }//GEN-LAST:event_jdamage_GRnumbertxtFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jdamage_GRdatetxt;
    private javax.swing.JTextField jdamage_GRnumbertxt;
    private javax.swing.JTextField jdamage_Numbertxt;
    private javax.swing.JComboBox jdamage_Reason_combo;
    private javax.swing.JTextArea jdamage_addresstxt;
    private javax.swing.JButton jdamage_backbtn;
    private javax.swing.JButton jdamage_clearbtn;
    private javax.swing.JTextField jdamage_contacttxt;
    private javax.swing.JTextField jdamage_damagedstocktxt;
    private javax.swing.JTextArea jdamage_desciptiontxt;
    private javax.swing.JTextField jdamage_distributornametxt;
    private javax.swing.JTextField jdamage_productnametxt;
    private javax.swing.JTextField jdamage_raminingstocktxt;
    private javax.swing.JTextField jdamage_sysDatetxt;
    private javax.swing.JTable jdamage_table;
    private javax.swing.JTextField jdamage_totalstocktxt;
    private javax.swing.JButton jdamage_updatebtn;
    // End of variables declaration//GEN-END:variables
}
