/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Account;


import DB.Dbconn;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



public class Bouncecheck extends javax.swing.JInternalFrame {
       
        int valid = 0;
        String str = "";
        Dbconn conn;
        String bankname,vendername,checkno,checkamount,date;
   
        
        
    JFrame frame = new JFrame();
    DefaultTableModel modelItem;
  //  private final DefaultTableModel modelItem;
    
    public Bouncecheck(JFrame parent, boolean modal) {
       
        initComponents();
         
        modelItem=(DefaultTableModel)jCheckbouncetable.getModel();
        refreshTable();
    }
   public void refreshTable()
    {
       
        
        try
        {
             conn=new Dbconn();
           
              ResultSet rs=conn.execute_query("select * from bouncecheck_detail where status=?", new String[]{"ACTIVE"});
              
          while(rs.next())
          {
             // bankname,vendername,checkno,checkamount,date;
          bankname=rs.getString("bank_name");
          vendername=rs.getString("vender_name");
          checkno=rs.getString("check_no");
          checkamount=rs.getString("check_amount");
          date=rs.getString("date");
          
           
           modelItem.addRow(new String[]{ bankname, vendername, checkno, checkamount, date});
             }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcheckbounce_vendername = new javax.swing.JTextField();
        jcheckbounce_checkno = new javax.swing.JTextField();
        jcheckbounce_amount = new javax.swing.JTextField();
        jcheckbounce_date = new javax.swing.JTextField();
        jcheckbounce_bankname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCheckbouncetable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jSaveButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jClearButton = new javax.swing.JButton();
        jBackButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("BouncedCheckDetail");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Bounced Cheque Details");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Bank Name");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Party Name");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Cheque Number");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Cheque Amount");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcheckbounce_vendername)
                    .addComponent(jcheckbounce_checkno)
                    .addComponent(jcheckbounce_amount)
                    .addComponent(jcheckbounce_date)
                    .addComponent(jcheckbounce_bankname, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckbounce_bankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckbounce_vendername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcheckbounce_checkno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcheckbounce_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcheckbounce_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckbouncetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bank Name", "Vender Name", "Check Number", "Check Amount", "Date"
            }
        ));
        jCheckbouncetable.setToolTipText("");
        jCheckbouncetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckbouncetableMouseClicked(evt);
            }
        });
        jCheckbouncetable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckbouncetableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCheckbouncetableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jCheckbouncetable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSaveButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jSaveButton.setText("Save");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        jDeleteButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jDeleteButton.setText("Delete");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jClearButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jClearButton.setText("Clear");
        jClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButtonActionPerformed(evt);
            }
        });

        jBackButton.setText("Back");
        jBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButtonActionPerformed
        jcheckbounce_bankname.setText("");
        jcheckbounce_vendername.setText("");    
        jcheckbounce_checkno.setText("");
        jcheckbounce_amount.setText("");
        jcheckbounce_date.setText("");
       
// TODO add your handling code here:
    }//GEN-LAST:event_jClearButtonActionPerformed

    private void jBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonActionPerformed
           this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jBackButtonActionPerformed

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
          // conn=new Dbconn();
           
        if (jcheckbounce_bankname.getText().equals("")) {
            str += "Plaese Enter Bank Name";
            valid = 1;
        } 
         if (jcheckbounce_vendername.getText().equals("[")) {
            str +="\n"+ "Plaese Enter Vender Name";
            valid = 1;
        } 
         if (jcheckbounce_checkno.getText().equals("")) {
            str +="\n"+ "Plaese Enter Check Number";
            valid = 1;
        } 
       
         if (jcheckbounce_amount.getText().equals("")) {
            str +="\n"+ "Plaese Enter Check Amount";
            valid = 1;
        } 
          if (jcheckbounce_date.getText().equals("")) {
            str +="\n"+ "Plaese Enter Check Date";
            valid = 1;
        }    
            
          
          
          
          if(valid==1)
        {
            JOptionPane.showMessageDialog(rootPane, str);
         }
        else
        {
           int s= JOptionPane.showConfirmDialog(null, "Are You Save this..", "SAVE RECORD", JOptionPane.YES_NO_OPTION); 
            
         if(s==0)
           {
                      
           
              int i=conn.insert_data("insert into bouncecheck_detail(bank_name,vender_name,check_no,"
                + "check_amount,date,status)"
                + "values (?,?,?,?,?,?)", new String[]{jcheckbounce_bankname.getText(),jcheckbounce_vendername.getText(),
                    jcheckbounce_checkno.getText(),jcheckbounce_amount.getText(),jcheckbounce_date.getText(),"ACTIVE"});
                  //JOptionPane.showMessageDialog(rootPane, "Data save");
         
             if (i > 0) 
               {
                JOptionPane.showMessageDialog(rootPane, "Data save");
               

               }
            else {
                    JOptionPane.showMessageDialog(rootPane, "Data not save");
              }
           
           }
         if(s==1)
         {
             this.dispose();
         }
             String col1,col2,col3,col4,col5;
            
            col1=jcheckbounce_bankname.getText();
            col2=jcheckbounce_vendername.getText();
            col3=jcheckbounce_checkno.getText();
            col4=jcheckbounce_amount.getText();
            col5=jcheckbounce_date.getText();
            
             
             conn=new Dbconn();
             // modelItem=(DefaultTableModel)jCheckbouncetable.getModel();
              modelItem.addRow(new String[]{col1,col2,col3,col4,col5});
            

               //Text Box Blank
               jcheckbounce_bankname.setText("");
                jcheckbounce_vendername.setText("");    
                jcheckbounce_checkno.setText("");
                jcheckbounce_amount.setText("");
                jcheckbounce_date.setText("");
                
    }
       
          
// TODO add your handling code here:
    }//GEN-LAST:event_jSaveButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
          int s= JOptionPane.showConfirmDialog(null, "Are You Realy Wants to Delete this..", "Delete", JOptionPane.YES_NO_OPTION);           
           if(s==0)
           {
               
           
          int selectedRow = jCheckbouncetable.getSelectedRow();
                            
                          if(selectedRow != -1) 
                          {
                           modelItem.removeRow(selectedRow);     
                           
// TODO add your handling code here:
    }//GEN-LAST:event_jDeleteButtonActionPerformed
                          else{
                              this.dispose();
                          }
           }
           }
    
    
    private void jCheckbouncetableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckbouncetableKeyPressed
       
        
        JTable target = (JTable)evt.getSource();  
       if((evt.getKeyCode()==KeyEvent.VK_UP)|| evt.getKeyCode()==KeyEvent.VK_DOWN)
   {   
    int selectedrow= target.getSelectedRow(); 
      Object selectedcellvalue = target.getValueAt(selectedrow,0);
             jcheckbounce_bankname.setText((String) selectedcellvalue);
              
                 selectedcellvalue = target.getValueAt(selectedrow, 1);
              jcheckbounce_vendername.setText((String) selectedcellvalue);
                
             selectedcellvalue = target.getValueAt(selectedrow, 2);
             jcheckbounce_checkno.setText((String) selectedcellvalue);
           
              selectedcellvalue = target.getValueAt(selectedrow, 3);
             jcheckbounce_amount.setText((String) selectedcellvalue);
              
                 selectedcellvalue = target.getValueAt(selectedrow, 4);
             jcheckbounce_date.setText((String) selectedcellvalue);
   }
    }//GEN-LAST:event_jCheckbouncetableKeyPressed

    private void jCheckbouncetableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckbouncetableKeyReleased

         JTable target = (JTable)evt.getSource();  
       if((evt.getKeyCode()==KeyEvent.VK_UP)|| evt.getKeyCode()==KeyEvent.VK_DOWN)
   {   
    int selectedrow= target.getSelectedRow(); 
      Object selectedcellvalue = target.getValueAt(selectedrow,0);
             jcheckbounce_bankname.setText((String) selectedcellvalue);
              
                 selectedcellvalue = target.getValueAt(selectedrow, 1);
              jcheckbounce_vendername.setText((String) selectedcellvalue);
                
             selectedcellvalue = target.getValueAt(selectedrow, 2);
             jcheckbounce_checkno.setText((String) selectedcellvalue);
           
              selectedcellvalue = target.getValueAt(selectedrow, 3);
             jcheckbounce_amount.setText((String) selectedcellvalue);
              
                 selectedcellvalue = target.getValueAt(selectedrow, 4);
             jcheckbounce_date.setText((String) selectedcellvalue);
   }
// TODO add your handling code here:
    }//GEN-LAST:event_jCheckbouncetableKeyReleased

    private void jCheckbouncetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckbouncetableMouseClicked
      
        if(evt.getClickCount()==1)
        {
           JTable target=(JTable)evt.getSource();
            int selectedrow = target.getSelectedRow();
            
           Object selectedcellvalue = target.getValueAt(selectedrow,0);
           jcheckbounce_bankname.setText((String) selectedcellvalue);
              
                selectedcellvalue = target.getValueAt(selectedrow, 1);
           jcheckbounce_vendername.setText((String) selectedcellvalue);
               
             selectedcellvalue = target.getValueAt(selectedrow, 2);
           jcheckbounce_checkno.setText((String) selectedcellvalue);
            
                selectedcellvalue = target.getValueAt(selectedrow, 3);
               jcheckbounce_amount.setText((String) selectedcellvalue);
               
               selectedcellvalue = target.getValueAt(selectedrow, 4);
            jcheckbounce_date.setText((String) selectedcellvalue);
              

        }
       
        

// TODO add your handling code here:
    }//GEN-LAST:event_jCheckbouncetableMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton;
    private javax.swing.JTable jCheckbouncetable;
    private javax.swing.JButton jClearButton;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jcheckbounce_amount;
    private javax.swing.JTextField jcheckbounce_bankname;
    private javax.swing.JTextField jcheckbounce_checkno;
    private javax.swing.JTextField jcheckbounce_date;
    private javax.swing.JTextField jcheckbounce_vendername;
    // End of variables declaration//GEN-END:variables
}
